// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Tgu7ldkgVuW4cyhIr-5WKmC2txIFVsg',
    appId: '1:402189719128:web:bd863b986258ecbbf91c2d',
    messagingSenderId: '402189719128',
    projectId: 'readalert-1f04d',
    authDomain: 'readalert-1f04d.firebaseapp.com',
    storageBucket: 'readalert-1f04d.firebasestorage.app',
    measurementId: 'G-PNMXWY9BLQ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbu1cb-MzWNLhPwl8GSK5eVCGY4HZ72w8',
    appId: '1:402189719128:ios:54935d6b2ff73e8df91c2d',
    messagingSenderId: '402189719128',
    projectId: 'readalert-1f04d',
    storageBucket: 'readalert-1f04d.firebasestorage.app',
    iosBundleId: 'com.example.readalert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbu1cb-MzWNLhPwl8GSK5eVCGY4HZ72w8',
    appId: '1:402189719128:ios:54935d6b2ff73e8df91c2d',
    messagingSenderId: '402189719128',
    projectId: 'readalert-1f04d',
    storageBucket: 'readalert-1f04d.firebasestorage.app',
    iosBundleId: 'com.example.readalert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1Tgu7ldkgVuW4cyhIr-5WKmC2txIFVsg',
    appId: '1:402189719128:web:b1236eb22cfc85daf91c2d',
    messagingSenderId: '402189719128',
    projectId: 'readalert-1f04d',
    authDomain: 'readalert-1f04d.firebaseapp.com',
    storageBucket: 'readalert-1f04d.firebasestorage.app',
    measurementId: 'G-9ZQZ99ENQQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp8yY9peWhyB8vxaVZwmy4Hncp9s4fc6I',
    appId: '1:402189719128:android:992d4d724e747afff91c2d',
    messagingSenderId: '402189719128',
    projectId: 'readalert-1f04d',
    storageBucket: 'readalert-1f04d.firebasestorage.app',
  );

}